language: julia
julia:
  - 1.1
matrix:
  include:
    - name: "Windows"
      os: windows
      language: shell
    - name: "Linux"
      dist: xenial
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -q
        - sudo apt-get install gfortran-9
        - sudo ln -fs /usr/bin/gfortran-9 /usr/bin/gfortran && gfortran --version

# commands to install dependencies: in this case use cmake to generate build environment
install: 
    - mkdir ./build
    - cd ./build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=. -G "MinGW Makefiles" ../ || cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=. ../

# commands to run tests: compile FLINT and link text executable
script:
    - cmake --build ./

# run tests
after_success:
    - ./TestFLINT
    - cat ./results.txt
    - mv ./results.txt ../media
    - cd ../media
    - julia -e 'using Pkg; Pkg.add(\"Coverage\"); Pkg.add(\"DifferentialEquations\");Pkg.add(\"LinearAlgebra\");Pkg.add(\"Printf\")'
    # run Julia script twice to let it compile things
    - julia -e 'JuliaDiffEq_CR3BP.jl'
    - julia -e 'JuliaDiffEq_CR3BP.jl'
